# Generated by Django 3.1.7 on 2021-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210323_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='headline_text',
        ),
        migrations.AddField(
            model_name='services',
            name='services_description',
            field=models.TextField(blank=True, help_text='Description written on the card'),
        ),
        migrations.AddField(
            model_name='services',
            name='services_title',
            field=models.CharField(blank=True, help_text='Title to display on webpage', max_length=70),
        ),
        migrations.AddField(
            model_name='services',
            name='services_url',
            field=models.URLField(blank=True, help_text='url to external website'),
        ),
    ]
